import = [
    "~/.config/alacritty/theme_lovelace.toml"
]

live_config_reload = false

[shell]
program = "/usr/bin/env"
args = ["zsh", "-l"]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 110, lines = 50 }
decorations_theme_variant = "Dark"
opacity = 0.9
blur = true

[font]
normal = { family = "gallant12x22", style = "Medium" }
bold = { style = "SemiBold" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [{ key = "N", mods = "Control | Shift", action = "CreateNewWindow" }]

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

