syntax enable
filetype plugin on
set textwidth=72
set wrapmargin=72
set filetype=mail
set nocompatible
set nobackup
set ruler
set tabstop=8
set shiftwidth=8
"set autoindent
set backspace=indent,eol,start

set encoding=utf-8
set fileencoding=utf-8
set termencoding=utf-8

" Mail (for Elm, trn, mutt, rn, slrn)
au BufNewFile,BufRead snd.\d\+,.letter,.letter.\d\+,.followup,.article,.article.\d\+,pico.\d\+,mutt-*-\d\+,mutt.\d\+,mutt\w\{6\},ae\d\+.txt,/tmp/SLRN[0-9A-Z.]\+,*.eml,/tmp/mutt-* setf mail  
