SPACESHIP_TIME_SHOW=false

SPACESHIP_USER_SHOW=always

SPACESHIP_DIR_TRUNC_REPO=true
SPACESHIP_DIR_TRUNC_PREFIX="../"
SPACESHIP_DIR_PREFIX=
SPACESHIP_DIR_SUFFIX=" | "

SPACESHIP_PROMPT_PREFIXES_SHOW=true

SPACESHIP_GIT_PREFIX=

SPACESHIP_RUBY_PREFIX=
SPACESHIP_RUBY_SYMBOL="rb:"

SPACESHIP_NODE_PREFIX=
SPACESHIP_NODE_SYMBOL="js:"

SPACESHIP_PYTHON_PREFIX=
SPACESHIP_PYTHON_SYMBOL="py:"

SPACESHIP_VENV_PREFIX="("
SPACESHIP_VENV_SUFFIX=")"

SPACESHIP_EXIT_CODE_SHOW=true
SPACESHIP_EXIT_CODE_SYMBOL="X "
SPACESHIP_EXIT_CODE_PREFIX="["
SPACESHIP_EXIT_CODE_SUFFIX="]"

SPACESHIP_PROMPT_ORDER=(
    user
    dir
    git
    ruby
    node
    python
    venv
    line_sep
    exit_code
    sudo
    char
)
