import = [
    "~/.config/alacritty/themes/themes/thelovelace.toml"
]

[window]
dimensions = { columns = 100, lines = 44 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "Berkeley Mono Variable", style = "Regular" }
bold = { style = "SemiBold" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [{ key = "N", mods = "Control", action = "CreateNewWindow" }]
