import = [
    "~/.config/alacritty/themes/themes/thelovelace.toml"
]

[window]
dimensions = { columns = 100, lines = 44 }
decorations_theme_variant = "Dark"

[font]
normal = { family = "Berkeley Mono Variable", style = "Regular" }
bold = { style = "SemiBold" }
size = 11

[cursor]
style = { shape = "Beam", blinking = "On" }

[keyboard]
bindings = [{ key = "N", mods = "Control | Shift", action = "CreateNewWindow" }]

[[hints.enabled]]
binding = { key = "U", mods = "Control|Shift" }
command = "xdg-open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Control"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

